comment:
  require_changes: no
  layout: "diff,files"
  status:
    project:
      project: off
      patch: off

#flags:
#  kube:
#    paths: ["kube"]
#  core:
#    paths: ["kube-core"]
#  client:
#    paths: ["kube-client"]
#  runtime:
#    paths: ["kube-runtime"]
#  derive:
#    paths: ["kube-derive"]
