name: "🚀 Feature Request"
description: "I have a specific suggestion for Kube!"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

  - type: dropdown
    attributes:
      label: Would you like to work on this feature?
      description: |
        **NOTE**: Let us know if you would like to submit a PR for this. We are more than happy to help you through the process.
      options:
        - "yes"
        - "no"
        - "maybe"

  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: |
        A concise description of what the problem is.
      placeholder: |
        I have an issue when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
    validations:
      required: true

  - type: textarea
    attributes:
      label: Documentation, Adoption, Migration Strategy
      description: |
        If you can, explain how users will be able to use this and how it might be documented. Maybe a mock-up?

  - type: dropdown
    attributes:
      label: Target crate for feature
      description: |
        **NOTE**: Select the crate(s) you think should be responsible for the feature
      multiple: true
      options:
        - kube-core
        - kube-client
        - kube-derive
        - kube-runtime
