---
apiVersion: v1
kind: Namespace
metadata:
  name: apps

---
# Scoped service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e
  namespace: apps
automountServiceAccountToken: true

---
# Access for the service account
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: apps
  name: e2e-role
rules:
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - create
    - get
    - watch
    - list
    - delete

---
# Binding the role to the account in apps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: e2e-binding
  namespace: apps
subjects:
- kind: ServiceAccount
  name: e2e
roleRef:
  kind: Role
  name: e2e-role
  apiGroup: rbac.authorization.k8s.io

---
# Main job
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e
  namespace: apps
  labels:
    app: e2e
spec:
  template:
    metadata:
      labels:
        app: e2e
    spec:
      serviceAccountName: e2e
      restartPolicy: Never
      containers:
      - name: e2e
        image: "clux/kube-e2e:latest"
        imagePullPolicy: IfNotPresent
