// Generated by darling macros, out of our control
#![allow(clippy::manual_unwrap_or_default)]
use darling::{FromDeriveInput, util::Override};
use proc_macro2::{Ident, Literal, Span, TokenStream};
use quote::{ToTokens, TokenStreamExt as _};
use syn::{Data, DeriveInput, Path, Visibility};

use crate::custom_resource::attrs::{
    Crates, KeyValuePair, KubeAttrs, KubeRootMeta, PrintColumn, Scale, SchemaMode,
};

mod attrs;

impl ToTokens for KeyValuePair {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let (k, v) = (&self.0, &self.1);
        tokens.append_all(quote! { (#k, #v) });
    }
}

impl PrintColumn {
    fn to_tokens(&self, k8s_openapi: &Path) -> TokenStream {
        let apiext = quote! {
            #k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1
        };

        let description = self
            .description
            .as_ref()
            .map_or_else(|| quote! { None }, |d| quote! { Some(#d.into()) });
        let format = self
            .format
            .as_ref()
            .map_or_else(|| quote! { None }, |f| quote! { Some(#f.into()) });
        let priority = self
            .priority
            .as_ref()
            .map_or_else(|| quote! { None }, |p| quote! { Some(#p.into()) });
        let json_path = &self.json_path;
        let name = &self.name;
        let type_ = &self.type_;

        quote! {
            #apiext::CustomResourceColumnDefinition {
                description: #description,
                format: #format,
                json_path: #json_path.into(),
                name: #name.into(),
                priority: #priority,
                type_: #type_.into(),
            }
        }
    }
}

impl Scale {
    fn to_tokens(&self, k8s_openapi: &Path) -> TokenStream {
        let apiext = quote! {
            #k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1
        };

        let label_selector_path = self
            .label_selector_path
            .as_ref()
            .map_or_else(|| quote! { None }, |p| quote! { Some(#p.into()) });
        let spec_replicas_path = &self.spec_replicas_path;
        let status_replicas_path = &self.status_replicas_path;

        quote! {
            #apiext::CustomResourceSubresourceScale {
                label_selector_path: #label_selector_path,
                spec_replicas_path: #spec_replicas_path.into(),
                status_replicas_path: #status_replicas_path.into()
            }
        }
    }
}

impl ToTokens for KubeRootMeta {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        self.0.to_tokens(tokens);
    }
}

pub(crate) fn derive(input: proc_macro2::TokenStream) -> proc_macro2::TokenStream {
    let derive_input: DeriveInput = match syn::parse2(input) {
        Err(err) => return err.to_compile_error(),
        Ok(di) => di,
    };
    // Limit derive to structs
    match derive_input.data {
        Data::Struct(_) | Data::Enum(_) => {}
        _ => {
            return syn::Error::new_spanned(
                &derive_input.ident,
                r#"Unions can not #[derive(CustomResource)]"#,
            )
            .to_compile_error();
        }
    }

    let kube_attrs = match KubeAttrs::from_derive_input(&derive_input) {
        Err(err) => return err.write_errors(),
        Ok(attrs) => attrs,
    };

    let KubeAttrs {
        group,
        kind,
        kind_struct,
        version,
        doc,
        namespaced,
        attributes,
        derives,
        schema: schema_mode,
        status,
        plural,
        singular,
        categories,
        shortnames,
        printcolumns,
        selectable,
        scale,
        validations,
        cel,
        storage,
        served,
        deprecated,
        crates:
            Crates {
                kube_core,
                kube,
                k8s_openapi,
                schemars,
                serde,
                serde_json,
                std,
            },
        annotations,
        labels,
    } = kube_attrs;

    let struct_name = kind_struct.unwrap_or_else(|| kind.clone());
    if derive_input.ident == struct_name {
        return syn::Error::new_spanned(
            derive_input.ident,
            r#"#[derive(CustomResource)] `kind = "..."` must not equal the struct name (this is generated)"#,
        )
        .to_compile_error();
    }
    let visibility = derive_input.vis;
    let ident = derive_input.ident;

    // 1. Create root object Foo and truncate name from FooSpec

    // Default visibility is `pub(crate)`
    // Default generics is no generics (makes little sense to re-use CRD kind?)
    // We enforce metadata + spec's existence (always there)
    // => No default impl
    let rootident = Ident::new(&struct_name, Span::call_site());
    let rootident_str = rootident.to_string();

    // if status set, also add that
    let StatusInformation {
        field: status_field,
        default: status_default,
        impl_hasstatus,
    } = process_status(&rootident, &status, &visibility, &kube_core);
    let has_status = status.is_some();
    let serialize_status = if has_status {
        quote! {
            if let Some(status) = &self.status {
                obj.serialize_field("status", &status)?;
            }
        }
    } else {
        quote! {}
    };
    let has_status_value = if has_status {
        quote! { self.status.is_some() }
    } else {
        quote! { false }
    };

    let mut derive_paths: Vec<Path> = vec![
        syn::parse_quote! { #serde::Deserialize },
        syn::parse_quote! { Clone },
        syn::parse_quote! { Debug },
    ];
    let mut has_default = false;
    for d in &derives {
        if d == "Default" {
            has_default = true; // overridden manually to avoid confusion
        } else {
            match syn::parse_str(d) {
                Err(err) => return err.to_compile_error(),
                Ok(d) => derive_paths.push(d),
            }
        }
    }

    // Enable schema generation by default as in v1 it is mandatory.
    let schema_mode = schema_mode.unwrap_or(SchemaMode::Derived);
    // We exclude fields `apiVersion`, `kind`, and `metadata` from our schema because
    // these are validated by the API server implicitly. Also, we can't generate the
    // schema for `metadata` (`ObjectMeta`) because it doesn't implement `JsonSchema`.
    let schemars_skip = schema_mode.derive().then_some(quote! { #[schemars(skip)] });
    if schema_mode.derive() && (!validations.is_empty() || cel) {
        derive_paths.push(syn::parse_quote! { #kube::KubeSchema });
    } else if schema_mode.derive() {
        derive_paths.push(syn::parse_quote! { #schemars::JsonSchema });
    }

    let struct_rules: Option<Vec<TokenStream>> =
        (!validations.is_empty()).then(|| validations.iter().map(|r| quote! {validation = #r,}).collect());
    let struct_rules = struct_rules.map(|r| quote! { #[x_kube(#(#r)*)]});

    let meta_annotations = if !annotations.is_empty() {
        quote! { Some(std::collections::BTreeMap::from([#((#annotations.0.to_string(), #annotations.1.to_string()),)*])) }
    } else {
        quote! { None }
    };

    let meta_labels = if !labels.is_empty() {
        quote! { Some(std::collections::BTreeMap::from([#((#labels.0.to_string(), #labels.1.to_string()),)*])) }
    } else {
        quote! { None }
    };

    let docstr =
        doc.unwrap_or_else(|| format!(" Auto-generated derived type for {ident} via `CustomResource`"));
    let quoted_serde = Literal::string(&serde.to_token_stream().to_string());
    let schemars_attribute = generate_schemars_attribute(schema_mode, &schemars);

    let root_obj = quote! {
        #[doc = #docstr]
        #[automatically_derived]
        #[allow(missing_docs)]
        #[derive(#(#derive_paths),*)]
        #(#[#attributes])*
        #[serde(rename_all = "camelCase")]
        #[serde(crate = #quoted_serde)]
        #schemars_attribute
        #struct_rules
        #visibility struct #rootident {
            #schemars_skip
            #visibility metadata: #k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta,
            #visibility spec: #ident,
            #status_field
        }
        impl #rootident {
            /// Spec based constructor for derived custom resource
            pub fn new(name: &str, spec: #ident) -> Self {
                Self {
                    metadata: #k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta {
                        annotations: #meta_annotations,
                        labels: #meta_labels,
                        name: Some(name.to_string()),
                        ..Default::default()
                    },
                    spec: spec,
                    #status_default
                }
            }
        }
        impl #serde::Serialize for #rootident {
            fn serialize<S: #serde::Serializer>(&self, ser: S) -> #std::result::Result<S::Ok, S::Error> {
                use #serde::ser::SerializeStruct;
                let mut obj = ser.serialize_struct(#rootident_str, 4 + usize::from(#has_status_value))?;
                obj.serialize_field("apiVersion", &<#rootident as #kube_core::Resource>::api_version(&()))?;
                obj.serialize_field("kind", &<#rootident as #kube_core::Resource>::kind(&()))?;
                obj.serialize_field("metadata", &self.metadata)?;
                obj.serialize_field("spec", &self.spec)?;
                #serialize_status
                obj.end()
            }
        }
    };

    // 2. Implement Resource trait
    let name = singular.unwrap_or_else(|| kind.to_ascii_lowercase());
    let plural = plural.unwrap_or_else(|| to_plural(&name));
    let (scope, scope_quote) = if namespaced {
        ("Namespaced", quote! { #kube_core::NamespaceResourceScope })
    } else {
        ("Cluster", quote! { #kube_core::ClusterResourceScope })
    };

    let api_ver = format!("{group}/{version}");
    let impl_resource = quote! {
        impl #kube_core::Resource for #rootident {
            type DynamicType = ();
            type Scope = #scope_quote;

            fn group(_: &()) -> std::borrow::Cow<'_, str> {
               #group.into()
            }

            fn kind(_: &()) -> std::borrow::Cow<'_, str> {
                #kind.into()
            }

            fn version(_: &()) -> std::borrow::Cow<'_, str> {
                #version.into()
            }

            fn api_version(_: &()) -> std::borrow::Cow<'_, str> {
                #api_ver.into()
            }

            fn plural(_: &()) -> std::borrow::Cow<'_, str> {
                #plural.into()
            }

            fn meta(&self) -> &#k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta {
                &self.metadata
            }

            fn meta_mut(&mut self) -> &mut #k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta {
                &mut self.metadata
            }
        }
    };

    // 3. Implement Default if requested
    let impl_default = if has_default {
        quote! {
            impl Default for #rootident {
                fn default() -> Self {
                    Self {
                        metadata: #k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta::default(),
                        spec: Default::default(),
                        #status_default
                    }
                }
            }
        }
    } else {
        quote! {}
    };

    // 4. Implement CustomResource

    // Compute a bunch of crd props
    let printers = {
        let printers: Vec<_> = printcolumns.iter().map(|p| p.to_tokens(&k8s_openapi)).collect();
        quote! { vec![ #(#printers),* ] }
    };
    let scale = scale.map_or_else(
        || quote! { None },
        |s| {
            let scale = s.to_tokens(&k8s_openapi);
            quote! { Some(#scale) }
        },
    );

    // Ensure it generates for the correct CRD version (only v1 supported now)
    let apiext = quote! {
        #k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1
    };
    let extver = quote! {
        #kube_core::crd::v1
    };

    let shortnames_slice = {
        let names = shortnames
            .iter()
            .map(|name| quote! { #name, })
            .collect::<TokenStream>();
        quote! { &[#names] }
    };

    // Unset attributes must be absent from the CRD, not explicit empty collections (#1680)
    let opt = |unset: bool, value: TokenStream| {
        if unset {
            quote! { None }
        } else {
            quote! { Some(#value) }
        }
    };
    let categories = opt(categories.is_empty(), quote! { vec![#(#categories.into()),*] });
    let short_names = opt(shortnames.is_empty(), quote! { vec![#(#shortnames.into()),*] });
    let printer_columns = opt(printcolumns.is_empty(), printers);
    let fields = selectable
        .iter()
        .map(|path| quote! { #apiext::SelectableField { json_path: #path.into() } });
    let selectable_fields = opt(selectable.is_empty(), quote! { vec![#(#fields),*] });
    let subresources = opt(!has_status, quote! {
        #apiext::CustomResourceSubresources {
            scale: #scale,
            status: Some(#apiext::CustomResourceSubresourceStatus(#serde_json::json!({}))),
        }
    });
    let (deprecated, deprecation_warning) = match deprecated {
        None => (quote! { None }, quote! { None }),
        Some(Override::Inherit) => (quote! { Some(true) }, quote! { None }),
        Some(Override::Explicit(warning)) => (quote! { Some(true) }, quote! { Some(#warning.into()) }),
    };
    let crd_meta_name = format!("{plural}.{group}");

    let schemagen = if schema_mode.use_in_crd() {
        quote! {
            // Don't use definitions and don't include `$schema` because these are not allowed.
            let generate = #schemars::generate::SchemaSettings::openapi3()
                .with(|s| {
                    s.inline_subschemas = true;
                    s.meta_schema = None;
                })
                .with_transform(#schemars::transform::AddNullable::default())
                .with_transform(#kube_core::schema::StructuralSchemaRewriter)
                .with_transform(#kube_core::schema::OptionalEnum)
                .with_transform(#kube_core::schema::OptionalIntOrString)
                .into_generator();
            let schema = #serde_json::to_value(generate.into_root_schema_for::<Self>())
                .and_then(#serde_json::from_value)
                .map(Some)
                .expect("valid JSONSchemaProps from schemars schema");
        }
    } else {
        // we could issue a compile time warning for this, but it would hit EVERY compile, which would be noisy
        // eprintln!("warning: kube-derive configured with manual schema generation");
        // users must manually set a valid schema in crd.spec.versions[*].schema - see examples: crd_derive_no_schema
        quote! {
            let schema: Option<#k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::JSONSchemaProps> = None;
        }
    };

    // Known constraints that are hard to enforce elsewhere
    let compile_constraints = quote! {}; // all modern features rolled out atm.

    // Implement the CustomResourceExt trait to allow users writing generic logic on top of them
    let impl_crd = quote! {
        impl #extver::CustomResourceExt for #rootident {

            fn crd() -> #apiext::CustomResourceDefinition {
                #schemagen

                #apiext::CustomResourceDefinition {
                    metadata: #k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta {
                        annotations: #meta_annotations,
                        labels: #meta_labels,
                        name: Some(#crd_meta_name.into()),
                        ..Default::default()
                    },
                    spec: #apiext::CustomResourceDefinitionSpec {
                        group: #group.into(),
                        names: #apiext::CustomResourceDefinitionNames {
                            categories: #categories,
                            kind: #kind.into(),
                            plural: #plural.into(),
                            short_names: #short_names,
                            singular: Some(#name.into()),
                            ..Default::default()
                        },
                        scope: #scope.into(),
                        versions: vec![#apiext::CustomResourceDefinitionVersion {
                            additional_printer_columns: #printer_columns,
                            deprecated: #deprecated,
                            deprecation_warning: #deprecation_warning,
                            name: #version.into(),
                            schema: Some(#apiext::CustomResourceValidation {
                                open_api_v3_schema: schema,
                            }),
                            selectable_fields: #selectable_fields,
                            served: #served,
                            storage: #storage,
                            subresources: #subresources,
                        }],
                        ..Default::default()
                    },
                    ..Default::default()
                }
            }

            fn crd_name() -> &'static str {
                #crd_meta_name
            }

            fn api_resource() -> #kube_core::dynamic::ApiResource {
                #kube_core::dynamic::ApiResource::erase::<Self>(&())
            }

            fn shortnames() -> &'static [&'static str] {
                #shortnames_slice
            }
        }
    };

    let impl_hasspec = generate_hasspec(&ident, &rootident, &kube_core);

    // Client-side CEL validation methods, generated when `#[kube(cel)]` is set.
    // Requires the downstream crate to enable `kube/cel` (the generated code references
    // `#kube_core::cel`). The bodies just delegate to `kube_core::cel::validate_cel{,_update}`, which
    // own the schema extraction + validation so they are compiled once in kube-core rather than
    // re-expanded at every derive site. Gated on a derived schema: a manual schema is not forced
    // through `KubeSchema`, so it would carry no `x-kubernetes-validations` and the methods would
    // silently validate nothing — reject that combination at compile time instead.
    let impl_validate_cel = if cel {
        if schema_mode.derive() {
            quote! {
                impl #rootident {
                    /// Validate this resource against its CEL creation rules (`x-kubernetes-validations`)
                    /// client-side, without an apiserver. `Ok(())` if all rules pass, otherwise the
                    /// aggregated failures.
                    pub fn validate_cel(&self) -> ::core::result::Result<(), #kube_core::cel::ValidationErrors> {
                        #kube_core::cel::validate_cel(self)
                    }

                    /// Validate this resource against its CEL transition rules (rules using `oldSelf`)
                    /// client-side, comparing against the `old` state. `Ok(())` if all rules pass,
                    /// otherwise the aggregated failures.
                    pub fn validate_cel_update(&self, old: &Self) -> ::core::result::Result<(), #kube_core::cel::ValidationErrors> {
                        #kube_core::cel::validate_cel_update(self, old)
                    }
                }
            }
        } else {
            quote! {
                ::core::compile_error!(
                    "#[kube(cel)] requires a derived schema; it cannot be combined with `schema = \"manual\"`"
                );
            }
        }
    } else {
        quote! {}
    };

    // Concat output
    quote! {
        #compile_constraints
        #root_obj
        #impl_resource
        #impl_default
        #impl_crd
        #impl_hasspec
        #impl_hasstatus
        #impl_validate_cel
    }
}

/// This generates the code for the `#kube_core::object::HasSpec` trait implementation.
///
/// All CRDs have a spec so it is implemented for all of them.
///
/// # Arguments
///
/// * `ident`: The identity (name) of the spec struct
/// * `root ident`: The identity (name) of the main CRD struct (the one we generate in this macro)
/// * `kube_core`: The path stream for the analogous kube::core import location from users POV
fn generate_hasspec(spec_ident: &Ident, root_ident: &Ident, kube_core: &Path) -> TokenStream {
    quote! {
        impl #kube_core::object::HasSpec for #root_ident {
            type Spec = #spec_ident;

            fn spec(&self) -> &#spec_ident {
                &self.spec
            }

            fn spec_mut(&mut self) -> &mut #spec_ident {
                &mut self.spec
            }
        }
    }
}

fn generate_schemars_attribute(schema_mode: SchemaMode, schemars_path: &Path) -> Option<TokenStream> {
    schema_mode.derive().then(|| {
        let schemars_path = schemars_path.to_token_stream().to_string();
        quote! { #[schemars(crate = #schemars_path)] }
    })
}

struct StatusInformation {
    /// The code to be used for the field in the main struct
    field: TokenStream,
    /// The initialization code to use in a `Default` and `::new()` implementation
    default: TokenStream,
    /// The implementation code for the `HasStatus` trait
    impl_hasstatus: TokenStream,
}

/// This processes the `status` field of a CRD.
///
/// As it is optional some features will be turned on or off depending on whether it's available or not.
///
/// # Arguments
///
/// * `root ident`: The identity (name) of the main CRD struct (the one we generate in this macro)
/// * `status`: The optional name of the `status` struct to use
/// * `visibility`: Desired visibility of the generated field
/// * `kube_core`: The path stream for the analogous kube::core import location from users POV
///
/// returns: A `StatusInformation` struct
fn process_status(
    root_ident: &Ident,
    status: &Option<Path>,
    visibility: &Visibility,
    kube_core: &Path,
) -> StatusInformation {
    if let Some(pth) = &status {
        StatusInformation {
            field: quote! {
                #[serde(skip_serializing_if = "Option::is_none")]
                #visibility status: Option<#pth>,
            },
            default: quote! { status: None, },
            impl_hasstatus: quote! {
                impl #kube_core::object::HasStatus for #root_ident {

                    type Status = #pth;

                    fn status(&self) -> Option<&#pth> {
                        self.status.as_ref()
                    }

                    fn status_mut(&mut self) -> &mut Option<#pth> {
                        &mut self.status
                    }
                }
            },
        }
    } else {
        let empty_quote = quote! {};
        StatusInformation {
            field: empty_quote.clone(),
            default: empty_quote.clone(),
            impl_hasstatus: empty_quote,
        }
    }
}

// Simple pluralizer.
// Duplicating the code from kube (without special casing) because it's simple enough.
// Irregular plurals must be explicitly specified.
fn to_plural(word: &str) -> String {
    // Words ending in s, x, z, ch, sh will be pluralized with -es (eg. foxes).
    if word.ends_with('s')
        || word.ends_with('x')
        || word.ends_with('z')
        || word.ends_with("ch")
        || word.ends_with("sh")
    {
        return format!("{word}es");
    }

    // Words ending in y that are preceded by a consonant will be pluralized by
    // replacing y with -ies (eg. puppies).
    if word.ends_with('y')
        && let Some(c) = word.chars().nth(word.len() - 2)
        && !matches!(c, 'a' | 'e' | 'i' | 'o' | 'u')
    {
        // Remove 'y' and add `ies`
        let mut chars = word.chars();
        chars.next_back();
        return format!("{}ies", chars.as_str());
    }

    // All other words will have "s" added to the end (eg. days).
    format!("{word}s")
}

#[cfg(test)]
mod tests {
    use std::{env, fs};

    use super::*;

    #[test]
    fn test_parse_default() {
        let input = quote! {
            #[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
            #[kube(group = "clux.dev", version = "v1", kind = "Foo", namespaced)]
            struct FooSpec { foo: String }
        };
        let input = syn::parse2(input).unwrap();
        let kube_attrs = KubeAttrs::from_derive_input(&input).unwrap();
        assert_eq!(kube_attrs.group, "clux.dev".to_string());
        assert_eq!(kube_attrs.version, "v1".to_string());
        assert_eq!(kube_attrs.kind, "Foo".to_string());
        assert!(kube_attrs.namespaced);
    }

    #[test]
    // The error cases are handled in tests/test_ui together with validating that the error messages are helpful
    fn test_parse_attribute_ok() {
        let input = quote! {
            #[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
            #[kube(group = "clux.dev", version = "v1", kind = "Foo", namespaced)]
            #[kube(attr="hello")]
            #[kube(attr="hello2")]
            struct FooSpec { foo: String }
        };
        let input = syn::parse2(input).unwrap();
        let kube_attrs = KubeAttrs::from_derive_input(&input).unwrap();
        assert_eq!(kube_attrs.group, "clux.dev".to_string());
        assert_eq!(kube_attrs.version, "v1".to_string());
        assert_eq!(kube_attrs.kind, "Foo".to_string());
        assert!(kube_attrs.namespaced);

        let expected_attrs = ["hello", "hello2"];
        assert_eq!(kube_attrs.attributes.len(), expected_attrs.len());
        for (i, attr) in kube_attrs
            .attributes
            .into_iter()
            .map(|el| el.to_token_stream().to_string())
            .enumerate()
        {
            assert_eq!(attr, expected_attrs[i],);
        }
    }

    #[test]
    fn test_derive_crd() {
        let path = env::current_dir().unwrap().join("tests").join("crd_enum_test.rs");
        let file = fs::File::open(path).unwrap();
        runtime_macros::emulate_derive_macro_expansion(file, &[("CustomResource", derive)]).unwrap();

        let path = env::current_dir()
            .unwrap()
            .join("tests")
            .join("crd_schema_test.rs");
        let file = fs::File::open(path).unwrap();
        runtime_macros::emulate_derive_macro_expansion(file, &[("CustomResource", derive)]).unwrap();
    }
}
