//! Client-side CEL validation generated by `#[kube(cel)]` / `#[x_kube(cel)]`.
//!
//! Run with: `cargo run --example crd_derive_cel --features cel`
//!
//! The same CEL rules the apiserver enforces server-side are evaluated locally here, without a
//! cluster. The root `#[kube(cel)]` generates `Resource::validate_cel(&self)` /
//! `validate_cel_update(&self, old)`; `#[x_kube(cel)]` generates a static
//! `Spec::validate_cel(value, old)` you can call on a fragment.
use kube::{CustomResource, KubeSchema};
use serde::{Deserialize, Serialize};

/// A toy autoscaler spec with CEL constraints.
///
/// - Root rule (`self` is the whole object): `minReplicas <= maxReplicas`.
/// - Spec-scoped rule (`self` is the spec): mirror of the same bound, usable on the spec alone.
/// - Field rules: `minReplicas >= 0`, and `tier` is immutable across updates (`self == oldSelf`).
#[derive(CustomResource, KubeSchema, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "example.kube.rs",
    version = "v1",
    kind = "Autoscaler",
    namespaced,
    cel,
    validation = "self.spec.minReplicas <= self.spec.maxReplicas"
)]
#[x_kube(cel, validation = "self.minReplicas <= self.maxReplicas")]
#[serde(rename_all = "camelCase")]
struct AutoscalerSpec {
    #[x_kube(validation = "self >= 0")]
    min_replicas: i32,
    max_replicas: i32,
    #[x_kube(validation = "self == oldSelf")]
    tier: String,
}

fn main() {
    // Root: a valid resource passes.
    let valid = Autoscaler::new("web", AutoscalerSpec {
        min_replicas: 1,
        max_replicas: 5,
        tier: "standard".into(),
    });
    println!("valid.validate_cel() -> {:?}", valid.validate_cel());
    assert!(valid.validate_cel().is_empty());

    // Root: min > max violates the creation rule.
    let invalid = Autoscaler::new("web", AutoscalerSpec {
        min_replicas: 9,
        max_replicas: 5,
        tier: "standard".into(),
    });
    println!("invalid.validate_cel() -> {:?}", invalid.validate_cel());
    assert!(!invalid.validate_cel().is_empty());

    // Root update: changing the immutable `tier` violates the transition rule.
    let changed = Autoscaler::new("web", AutoscalerSpec {
        min_replicas: 1,
        max_replicas: 5,
        tier: "premium".into(),
    });
    println!(
        "changed.validate_cel_update(&valid) -> {:?}",
        changed.validate_cel_update(&valid)
    );
    assert!(!changed.validate_cel_update(&valid).is_empty());

    // Sub-struct: validate a serialized spec fragment directly, no resource needed.
    let fragment = serde_json::json!({"minReplicas": 3, "maxReplicas": 1, "tier": "standard"});
    let errors = AutoscalerSpec::validate_cel(&fragment, None);
    println!("AutoscalerSpec::validate_cel(fragment) -> {errors:?}");
    assert!(!errors.is_empty());

    println!("all CEL validations behaved as expected");
}
