---
apiVersion: v1
kind: Namespace
metadata:
  name: apps

---
# Scoped service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dapp
  namespace: apps
automountServiceAccountToken: true

---
# Access for the service account
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: apps
  name: dapp-role
rules:
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - create
    - get
    - watch
    - list
    - delete

---
# Binding the role to the account in apps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dapp-binding
  namespace: apps
subjects:
- kind: ServiceAccount
  name: dapp
roleRef:
  kind: Role
  name: dapp-role
  apiGroup: rbac.authorization.k8s.io

---
# Main job
apiVersion: batch/v1
kind: Job
metadata:
  name: dapp
  namespace: apps
  labels:
    app: dapp
spec:
  template:
    metadata:
      labels:
        app: dapp
    spec:
      serviceAccountName: dapp
      restartPolicy: Never
      containers:
      - name: dapp
        image: "clux/kube-dapp:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          value: "apps"
