name: clippy
on:
  pull_request:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'

jobs:
  clippy_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: extractions/setup-just@v4
      - run: just clippy # keep CI clippy identical to local
