name: coverage

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.rs"
      - "**.toml"
      - "**.yml"

# Spend CI time only on latest ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  tarpaulin-codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install tarpaulin
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin@0.32.8
      - uses: nolar/setup-k3d-k3s@v1
        with:
          channel: "v1.32" # MK8SV
          # k3d-kube
          k3d-name: kube
          k3d-args: "-p 10250:10250 --no-rollback --k3s-arg --disable=traefik,servicelb,metrics-server@server:*"

      - name: Import test images into k3d
        run: |
          docker pull busybox:stable
          k3d image import busybox:stable -c kube --mode direct

      - name: Run cargo-tarpaulin
        run: |
          rustup run stable cargo tarpaulin -o xml --skip-clean
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
